app:
  persistence: jdbc

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://123.56.218.192/gbdjt_product?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:gbdjt_product}
    password: ${SPRING_DATASOURCE_PASSWORD:Tia2ZLGw4jhXYEdB}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: DajiangtangHikariPool
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:10}
      minimum-idle: ${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE:2}
      connection-timeout: ${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT:600000}
      max-lifetime: ${SPRING_DATASOURCE_HIKARI_MAX_LIFETIME:1800000}
